"""
Sample schedule output utility.

Loads a generated schedule (defaulting to output/schedule_cp_sat.csv) and
renders it in several human-friendly formats:

  1. Matchday grid      — each gameweek on its own block
  2. Team season card   — one team's 38 fixtures with H/A, opponent, kickoff
  3. Derby highlights   — all high-profile derby pairings with leg gap
  4. Festive snapshot   — Boxing Day, Dec 28, and New Year's Day fixtures

Usage:
    python tools/sample_schedule.py
    python tools/sample_schedule.py --csv output/schedule_ilp.csv
    python tools/sample_schedule.py --team LIV
    python tools/sample_schedule.py --rounds 1-5
    python tools/sample_schedule.py --section derbies
"""
from __future__ import annotations

import argparse
import csv
import sys
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from core.data_loader import load_teams
from core.models import Fixture, Slot, ScheduledFixture, Schedule

# ---------------------------------------------------------------------------
# CSV loader
# ---------------------------------------------------------------------------

def load_csv(path: Path) -> Schedule:
    """Load a schedule CSV (as written by the solvers) into a Schedule object."""
    rows = []
    with open(path, newline="") as f:
        for row in csv.DictReader(f):
            slot = Slot(
                date=date.fromisoformat(row["date"]),
                kickoff=row["kickoff"],
                day_of_week=row["day"],
            )
            fixture = Fixture(
                fixture_id=row["fixture_id"],
                home_team_id=row["home"],
                away_team_id=row["away"],
            )
            rows.append(ScheduledFixture(fixture=fixture, slot=slot))
    season = path.stem.replace("schedule_", "").replace("_", " ").title()
    return Schedule(season=season, fixtures=rows)


# ---------------------------------------------------------------------------
# Round inference (based on fixture_id Fxxx generated by generate_epl.py)
# ---------------------------------------------------------------------------

def _round_num(fid: str) -> int:
    """F001–F010 → GW1, F011–F020 → GW2, …, F371–F380 → GW38."""
    try:
        n = int(fid[1:])
        return (n - 1) // 10 + 1
    except ValueError:
        return 0


# ---------------------------------------------------------------------------
# 1. Matchday grid
# ---------------------------------------------------------------------------

def print_matchday_grid(
    schedule: Schedule,
    teams: dict,
    round_range: tuple[int, int] = (1, 5),
) -> None:
    """Print a block-per-gameweek grid for the given round range."""
    by_round: dict[int, list[ScheduledFixture]] = {}
    for sf in schedule.fixtures:
        rn = _round_num(sf.fixture.fixture_id)
        by_round.setdefault(rn, []).append(sf)

    name = {t: teams[t].name for t in teams}
    r_from, r_to = round_range
    w = 70

    print()
    print("=" * w)
    print(f"  MATCHDAY GRID  — Gameweeks {r_from}–{r_to}   [{schedule.season}]")
    print("=" * w)

    for rn in range(r_from, r_to + 1):
        fixtures = sorted(by_round.get(rn, []), key=lambda s: (s.slot.date, s.slot.kickoff))
        if not fixtures:
            continue
        date_range = _date_range_str(fixtures)
        print(f"\n  ── GW{rn:02d}  {date_range} ──")
        print(f"  {'Home':<22} {'Away':<22}  {'Date':<12} {'Day':<9} {'KO'}")
        print(f"  {'-'*22} {'-'*22}  {'-'*12} {'-'*9} {'-'*5}")
        for sf in fixtures:
            home = name.get(sf.home_team_id, sf.home_team_id)
            away = name.get(sf.away_team_id, sf.away_team_id)
            print(
                f"  {home:<22} {away:<22}  "
                f"{str(sf.slot.date):<12} {sf.slot.day_of_week:<9} {sf.slot.kickoff}"
            )

    print()


# ---------------------------------------------------------------------------
# 2. Team season card
# ---------------------------------------------------------------------------

def print_team_card(
    schedule: Schedule,
    teams: dict,
    team_id: str,
) -> None:
    """Print a single team's 38-fixture season schedule."""
    team_id = team_id.upper()
    if team_id not in teams:
        print(f"Unknown team: {team_id}")
        return

    team_name = teams[team_id].name
    fixtures = sorted(
        schedule.fixtures_for_team(team_id),
        key=lambda s: (s.slot.date, s.slot.kickoff),
    )
    name = {t: teams[t].name for t in teams}
    w = 70

    print()
    print("=" * w)
    print(f"  {team_name.upper()} — 2025/26 FIXTURE LIST  [{schedule.season}]")
    print("=" * w)
    print(f"  {'#':<3} {'H/A':<4} {'Opponent':<22} {'Date':<12} {'Day':<9} {'KO':<6} GW")
    print(f"  {'-'*3} {'-'*4} {'-'*22} {'-'*12} {'-'*9} {'-'*6} --")

    for i, sf in enumerate(fixtures, 1):
        is_home = sf.home_team_id == team_id
        ha = "H" if is_home else "A"
        opponent = sf.away_team_id if is_home else sf.home_team_id
        opp_name = name.get(opponent, opponent)
        rn = _round_num(sf.fixture.fixture_id)
        flag = " ★" if _is_derby(sf, team_id, teams) else ""
        print(
            f"  {i:<3} {ha:<4} {opp_name:<22} "
            f"{str(sf.slot.date):<12} {sf.slot.day_of_week:<9} {sf.slot.kickoff:<6} {rn}{flag}"
        )

    h_count = sum(1 for sf in fixtures if sf.home_team_id == team_id)
    print(f"\n  Total: {len(fixtures)} fixtures  ({h_count}H / {len(fixtures)-h_count}A)   ★ = derby\n")


def _is_derby(sf: ScheduledFixture, team_id: str, teams: dict) -> bool:
    opponent = sf.away_team_id if sf.home_team_id == team_id else sf.home_team_id
    return opponent in teams[team_id].rivalries


# ---------------------------------------------------------------------------
# 3. Derby highlights
# ---------------------------------------------------------------------------

def print_derby_highlights(schedule: Schedule, teams: dict) -> None:
    """Print all high-profile derby pairs with dates and leg gap."""
    from core.data_loader import load_high_profile_derbies
    derbies = load_high_profile_derbies()
    name = {t: teams[t].name for t in teams}
    w = 70

    print()
    print("=" * w)
    print(f"  DERBY HIGHLIGHTS  [{schedule.season}]")
    print("=" * w)

    for team_a, team_b in derbies:
        leg1 = next(
            (sf for sf in schedule.fixtures
             if sf.home_team_id == team_a and sf.away_team_id == team_b), None
        )
        leg2 = next(
            (sf for sf in schedule.fixtures
             if sf.home_team_id == team_b and sf.away_team_id == team_a), None
        )
        if not leg1 or not leg2:
            continue

        if leg1.slot.date > leg2.slot.date:
            leg1, leg2 = leg2, leg1

        gap = (leg2.slot.date - leg1.slot.date).days
        gap_flag = "  ⚠ < 56 days" if gap < 56 else ""

        derby_label = f"{name[team_a]} vs {name[team_b]}"
        print(f"\n  ▶ {derby_label}")
        print(
            f"    Leg 1: {leg1.slot.date}  {leg1.slot.day_of_week:<9}  "
            f"{leg1.slot.kickoff}  "
            f"({name[leg1.home_team_id]} H)"
        )
        print(
            f"    Leg 2: {leg2.slot.date}  {leg2.slot.day_of_week:<9}  "
            f"{leg2.slot.kickoff}  "
            f"({name[leg2.home_team_id]} H)  "
            f"gap: {gap} days{gap_flag}"
        )

    print()


# ---------------------------------------------------------------------------
# 4. Festive snapshot
# ---------------------------------------------------------------------------

def print_festive_snapshot(schedule: Schedule, teams: dict) -> None:
    """Print Boxing Day, Dec 28, and New Year's Day fixtures."""
    festive_dates = {
        date(2025, 12, 26): "Boxing Day",
        date(2025, 12, 28): "Dec 28",
        date(2026,  1,  1): "New Year's Day",
    }
    name = {t: teams[t].name for t in teams}
    w = 70

    print()
    print("=" * w)
    print(f"  FESTIVE PERIOD FIXTURES  [{schedule.season}]")
    print("=" * w)

    by_date: dict[date, list[ScheduledFixture]] = {}
    for sf in schedule.fixtures:
        by_date.setdefault(sf.slot.date, []).append(sf)

    for d, label in festive_dates.items():
        day_fixtures = sorted(by_date.get(d, []), key=lambda s: s.slot.kickoff)
        print(f"\n  {label} ({d})")
        if not day_fixtures:
            print("    — no fixtures scheduled —")
        else:
            print(f"  {'Home':<22} {'Away':<22}  {'KO'}")
            print(f"  {'-'*22} {'-'*22}  {'-'*5}")
            for sf in day_fixtures:
                print(
                    f"  {name.get(sf.home_team_id, sf.home_team_id):<22} "
                    f"{name.get(sf.away_team_id, sf.away_team_id):<22}  "
                    f"{sf.slot.kickoff}"
                )
        print(f"  ({len(day_fixtures)} fixtures)")

    print()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _date_range_str(fixtures: list[ScheduledFixture]) -> str:
    dates = [sf.slot.date for sf in fixtures]
    lo, hi = min(dates), max(dates)
    if lo == hi:
        return str(lo)
    return f"{lo} – {hi}"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Sample schedule output utility")
    parser.add_argument(
        "--csv", default=str(ROOT / "output" / "schedule_cp_sat.csv"),
        help="Path to schedule CSV (default: output/schedule_cp_sat.csv)",
    )
    parser.add_argument("--team", default="ARS", help="Team ID for team card (default: ARS)")
    parser.add_argument(
        "--rounds", default="1-5",
        help="Round range for matchday grid, e.g. '1-5' (default: 1-5)",
    )
    parser.add_argument(
        "--section", choices=["all", "grid", "team", "derbies", "festive"],
        default="all", help="Which section to print (default: all)",
    )
    args = parser.parse_args()

    csv_path = Path(args.csv)
    if not csv_path.exists():
        print(f"Schedule CSV not found: {csv_path}")
        print("Run a solver first:  python -m solvers.cp_sat.main")
        sys.exit(1)

    r_parts = args.rounds.split("-")
    round_range = (int(r_parts[0]), int(r_parts[-1]))

    teams    = load_teams()
    schedule = load_csv(csv_path)
    print(f"\nLoaded {len(schedule.fixtures)} fixtures from {csv_path.name}")

    section = args.section
    if section in ("all", "grid"):
        print_matchday_grid(schedule, teams, round_range)
    if section in ("all", "team"):
        print_team_card(schedule, teams, args.team)
    if section in ("all", "derbies"):
        print_derby_highlights(schedule, teams)
    if section in ("all", "festive"):
        print_festive_snapshot(schedule, teams)


if __name__ == "__main__":
    main()
